### ISSUE TITLE
Confirm Windows 11 supported - student having package installation errors

### ISSUE THREAD

**Issue by benjamin-jacobson** [learn-co-curriculum/dsc-data-science-env-config#3]
A student on OS Windows 11 was unable to install the **learn-env** environment, getting multiple package NotFound errors (>20 see below image). This successfully worked on Windows 10. Suggest reviewing for Windows 11, may need to be a separate Yaml file/instructions for 10 vs 11. 

![image](https://user-images.githubusercontent.com/43805163/146693656-6de0e750-48b3-4bea-9360-1e0ce933b864.png)

**Comment by ismayc** [comment]
@benjamin-jacobson I'm not able to reproduce on Windows 11. The installation goes through OK for me. I wonder if there was an internet disconnection here? I recommend the student trying `conda env create -f win_environment.yml` again.
